---
# tasks file for metricbeat
#SEE@ https://github.com/sadsfae/ansible-elk/tree/master/install/roles/metricbeat
- name: install the Metricbeat-6.5.4-x86_64.rpm
  yum: 
    name: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.5.4-x86_64.rpm
    state: present

- name: Generate metricbeat configuration template
  template:
    src=metricbeat.yml.j2
    dest=/etc/metricbeat/metricbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  register: metricbeat_needs_restart

- name: Start metricbeat service
  command: systemctl start metricbeat.service
  ignore_errors: true
  become: true
  when: metricbeat_needs_restart != 0

- name: Setup metricbeat service
  service: 
    name: metricbeat 
    state: started 
    enabled: true
  become: true
